In [1]:
from pathlib import Path
import json, re
import pandas as pd

BASE = Path(r"C:\Users\PC\Desktop\chatbot\dataset")  # 네 경로
OUT  = BASE / "built"
OUT.mkdir(parents=True, exist_ok=True)

list(BASE.glob("*"))

[WindowsPath('C:/Users/PC/Desktop/chatbot/dataset/.ipynb_checkpoints'),
 WindowsPath('C:/Users/PC/Desktop/chatbot/dataset/build_datasets.py'),
 WindowsPath('C:/Users/PC/Desktop/chatbot/dataset/built'),
 WindowsPath('C:/Users/PC/Desktop/chatbot/dataset/dataset'),
 WindowsPath('C:/Users/PC/Desktop/chatbot/dataset/discovery_3.csv'),
 WindowsPath('C:/Users/PC/Desktop/chatbot/dataset/discovery_4.json'),
 WindowsPath('C:/Users/PC/Desktop/chatbot/dataset/discovery_5.json'),
 WindowsPath('C:/Users/PC/Desktop/chatbot/dataset/entry_lectures_title.csv'),
 WindowsPath('C:/Users/PC/Desktop/chatbot/dataset/entry_test_and_recommend.ipynb'),
 WindowsPath('C:/Users/PC/Desktop/chatbot/dataset/entry_textbook.csv'),
 WindowsPath('C:/Users/PC/Desktop/chatbot/dataset/newlectures_3.csv'),
 WindowsPath('C:/Users/PC/Desktop/chatbot/dataset/newlectures_4.json'),
 WindowsPath('C:/Users/PC/Desktop/chatbot/dataset/newlectures_5.json'),
 WindowsPath('C:/Users/PC/Desktop/chatbot/dataset/데이터 정제.ipynb')]

In [2]:
def peek_csv(path, n=3):
    df = pd.read_csv(path, dtype="object").fillna("")
    print(f"[CSV] {path.name}  rows={len(df)}")
    print("columns:", list(df.columns))
    display(df.head(n))

def peek_json(path, n=3):
    print(f"[JSON] {path.name}")
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        # 혹시 JSONL일 수도 있어 대비
        data = [json.loads(line) for line in path.read_text(encoding="utf-8").splitlines() if line.strip()]
    print("type:", type(data))
    if isinstance(data, list) and data:
        print("sample keys:", list(data[0].keys()))
        display(pd.DataFrame(data[:n]))
    else:
        print("top-level keys:", list(data.keys()))
        arr = data.get("data") or data.get("items") or []
        print("wrapped array length:", len(arr))
        if arr:
            print("wrapped sample keys:", list(arr[0].keys()))
            display(pd.DataFrame(arr[:n]))

# 확인: discovery 3/4/5, newlectures 3/4/5
peek_csv(BASE/"discovery_3.csv")
peek_json(BASE/"discovery_4.json")
peek_json(BASE/"discovery_5.json")

peek_csv(BASE/"newlectures_3.csv")
peek_json(BASE/"newlectures_4.json")
peek_json(BASE/"newlectures_5.json")

[CSV] discovery_3.csv  rows=38
columns: ['_id', 'title', 'summary', 'isopen', 'categoryCode', 'difficulty', 'requiredTime', 'lang', 'goal', 'description', 'elements', 'content', 'seContent.document', 'seContent.documentId', 'comment', 'likeCnt', 'visit', 'participantCnt', 'codes', 'progressDone', 'sharePopup', 'description.1', 'basicProject', 'removed', 'updated', 'created']

,_id,title,summary,isopen,categoryCode,difficulty,requiredTime,lang,goal,description,...,visit,participantCnt,codes,progressDone,sharePopup,description.1,basicProject,removed,updated,created
0,ObjectId(61d2a6ea94a125003f94e23c),클릭! 나무 키우기,클릭하다 보니 어느새 나무가 다 자랐다,true,game,1,1,ko,클릭으로 즐기는 무한의 재미! 클리커 게임을 만들어 보자.,1. 클릭 수를 세는 변수를 만들어요.\n2. 특정 수만큼 클릭하면 모양을 바꿔요.,...,0,622,[],5,"{""image"":{""$oid"":""62561b4a2c490d001ae1a588""},""...",1. 클릭 수를 세는 변수를 만들어요.\n2. 특정 수만큼 클릭하면 모양을 바꿔요.,ObjectId(610b86f2aa9c197d7b7ee92b),,2023-01-04T09:07:50.202Z,2022-01-03T07:34:02.050Z
1,ObjectId(61d3c4f994a125003f94e286),푹신푹신 스티커,밋밋한 사진은 내 사진첩에 있을 수 없어! 인생샷에 인생 스티커를 더하자!,false,living,3,1,ko,사진에 스티커를 붙이는 앱을 만들어요.,1. 사진에 붙일 수 있는 스티커를 만들어요.\n2. 스티커 오브젝트의 복제본을 만...,...,0,2,[],7,"{""image"":{""$oid"":""61d3c7dae09991164b339d72""},""...",1. 사진에 붙일 수 있는 스티커를 만들어요.\n2. 스티커 오브젝트의 복제본을 만...,,2022-05-02T08:11:51.063Z,2022-05-02T08:11:51.063Z,2022-01-04T03:54:33.034Z
2,ObjectId(61d67680ec9979003fb71faf),퐁 PONG,최초의 아케이드 비디오 게임 '퐁(PONG)',false,game,2,2,ko,퐁 게임을 나만의 스타일로 만들어 보자.,1. 공 오브젝트가 움직이게 해요.\n2. 방향키로 패들 오브젝트가 움직여요.\n3...,...,0,0,[],6,"{""image"":{""$oid"":""61d679b6df4d1c9eca6f2925""},""...",1. 공 오브젝트가 움직이게 해요.\n2. 방향키로 패들 오브젝트가 움직여요.\n3...,,2022-05-02T08:11:48.177Z,2022-05-02T08:11:48.177Z,2022-01-06T04:56:32.994Z

[JSON] discovery_4.json
type: <class 'list'>
sample keys: ['_id', 'isopen', 'categoryCode', 'difficulty', 'requiredTime', 'lang', 'elements', 'comment', 'likeCnt', 'visit', 'participantCnt', 'codes', 'progressDone', 'title', 'summary', 'goal', 'description', 'content', 'seContent', 'created', 'updated', 'removed']

,_id,isopen,categoryCode,difficulty,requiredTime,lang,elements,comment,likeCnt,visit,...,summary,goal,description,content,seContent,created,updated,removed,basicProject,sharePopup
0,{'$oid': '6298489812747d0a9182c86d'},False,game,1,1,ko,[이벤트],0,0,0,...,.,.,.,"<div class=""se-viewer se-theme-default"" lang=""...","{'documentId': '62984e7e12747d0a9182d5a7', 'do...",{'$date': '2022-06-02T05:20:24.727Z'},{'$date': '2022-06-09T01:10:44.858Z'},{'$date': '2022-06-09T01:10:44.856Z'},NaN,NaN
1,{'$oid': '62a015a5f2cd990f3c956c62'},True,knowledge,2,2,ko,"[장면, 글상자, 모양]",9,7,0,...,아름다운 우리들의 지구를 위해,환경 보호의 중요성을 알리는 작품을 만들어요.,"1. 환경 보호의 필요성을 조사하고, 장면을 추가해 설명해 주세요.\n2. 다양한 ...","<div class=""se-viewer se-theme-default"" lang=""...","{'documentId': '6437b1401e161900305c2535', 'do...",{'$date': '2022-06-08T03:21:09.539Z'},{'$date': '2023-04-13T07:37:36.295Z'},NaN,{'$oid': '62a1ac7ded6e5e02de824de2'},{'image': {'$oid': '62a1bf127fb0cc376787e9ca'}...
2,{'$oid': '62e8bd47dc8d500030648032'},False,game,1,1,ko,[이벤트],0,0,0,...,테스트,테스트,테스트,"<div class=""se-viewer se-theme-default"" lang=""...","{'documentId': '62e8bd47dc8d500030648031', 'do...",{'$date': '2022-08-02T05:59:35.899Z'},{'$date': '2022-08-02T06:00:43.37Z'},{'$date': '2022-08-02T06:00:43.37Z'},NaN,NaN

[JSON] discovery_5.json
type: <class 'list'>
sample keys: ['_id', 'isopen', 'categoryCode', 'difficulty', 'requiredTime', 'lang', 'elements', 'comment', 'likeCnt', 'visit', 'participantCnt', 'codes', 'progressDone', 'title', 'summary', 'goal', 'description', 'content', 'seContent', 'created', 'updated', 'basicProject', 'sharePopup']

,_id,isopen,categoryCode,difficulty,requiredTime,lang,elements,comment,likeCnt,visit,...,summary,goal,description,content,seContent,created,updated,basicProject,sharePopup,removed
0,{'$oid': '65e9841eea553c0035981f02'},True,arts,1,1,ko,"[순차, 반복]",4,5,0,...,4초 반복이 멋진 음악이 되는 순간!,다양한 소리를 쌓아 나만의 루프스테이션을 만들어요.,1. 4초 길이의 기본 비트를 만들어요.\n2. 4초 길이의 다른 소리들을 쌓아 계...,"<div class=""se-viewer se-theme-default"" lang=""...","{'documentId': '65e984536ba8690035510342', 'do...",{'$date': '2024-03-07T09:08:46.399Z'},{'$date': '2024-04-25T08:36:22.947Z'},{'$oid': '65e978e593b63300330e4021'},{'image': {'$oid': '65fa875f0da18dea84cc36f8'}...,NaN
1,{'$oid': '65f16eedea553c00359909b1'},True,game,2,2,ko,"[반복, 조건, 변수, 좌표]",5,11,0,...,강렬한 스파이크! 박진감 넘치는 배구 게임,공을 토스하고 스파이크를 날려보는 재미! 배구 게임을 만들어 보자.,1. 공이 캐릭터에 닿으면 튕겨 나가게 해요.\n2. 캐릭터들을 움직여요.\n3. ...,"<div class=""se-viewer se-theme-default"" lang=""...","{'documentId': '65f16eed6ba8690035510343', 'do...",{'$date': '2024-03-13T09:16:29.972Z'},{'$date': '2024-04-25T08:36:45.408Z'},{'$oid': '65f170b3991acd088d467d43'},{'image': {'$oid': '65fa86fa1641e134aeb89609'}...,NaN
2,{'$oid': '65fa8a1cea553c003599c859'},False,game,3,3,ko,"[인공지능, 지도학습, 단순선형회귀]",0,0,0,...,손 안 대고 과일 따는 스마트한 방법,단순 선형회귀 AI 모델을 만들어 반복적인 과일 따기 작업을 자동화해요.,1. 과일 따기의 점수 얻는 패턴을 익혀요.\n2. 과일의 X 좌푯값을 독립 변수로...,"<div class=""se-viewer se-theme-default"" lang=""...","{'documentId': '660a62a084263d5f5fa5ad56', 'do...",{'$date': '2024-03-20T07:02:52.606Z'},{'$date': '2024-04-24T12:37:01.325Z'},{'$oid': '65f423a7d4f1fb08699983c8'},{'image': {'$oid': '65fd8baea1235316ab0e215c'}...,{'$date': '2024-04-24T12:37:01.323Z'}

[CSV] newlectures_3.csv  rows=250033
columns: ['_id', 'title', 'description', 'goals', 'category', 'requiredTime', 'difficulty', 'user', 'curriculum', 'visit', 'visitedUsers', 'savedUsers', 'like', 'comment', 'likeCnt', 'created', 'updated', 'studyCnt', 'isForHomework', 'origin', 'parent', 'studies', 'progress']

,_id,title,description,goals,category,requiredTime,difficulty,user,curriculum,visit,...,comment,likeCnt,created,updated,studyCnt,isForHomework,origin,parent,studies,progress
0,ObjectId(63b0b90504f9b1002ce5764b),벽 부수기,벽을 많이 부숴 이기세요,"[""인작이 목표""]",,5,3,ObjectId(637df4e8738dc0004ac9df0d),,30,...,0,0,2022-12-31T22:34:48.504Z,2022-12-31T22:34:59.488Z,0,false,,,"[{""$oid"":""63b0b90504f9b1002ce5764c""}]",
1,ObjectId(63b0659ede65ed001a3127c5),동물 친구 이야기 만들기,▶ 무엇을 만들어 볼까?\n강아지와 고양이가 대화하고 달리는 모습을 만들어봅시다.\...,"[""순서대로 블록을 조립하여 오브젝트간 대화를 만들 수 있다."",""두 개의 오브젝트...",,3,1,ObjectId(63b0659dde65ed001a3127b9),,0,...,0,0,2022-12-31T16:38:54.048Z,2022-12-31T16:38:54.048Z,0,false,,ObjectId(59018c767baa939aeae08910),"[{""$oid"":""59004d7dc5a92b3617557294""}]",
2,ObjectId(63b03eb3c69327004916022b),Q&A,저의 여러가지 궁금하던 점을 풀어보는 볼수있도록 준비하는 기간,"[""엔둥이들이 저에 대헤 궁금한걸 푸는 그런 시간을 준비 ""]",,1,1,ObjectId(6374ce3714f7280151ec2f8a),,2,...,0,0,2022-12-31T13:52:51.449Z,2022-12-31T13:53:05.637Z,0,false,,,"[{""$oid"":""63b03eb3c69327004916022c""}]",

[JSON] newlectures_4.json
type: <class 'list'>
sample keys: ['_id', 'goals', 'visit', 'visitedUsers', 'savedUsers', 'like', 'comment', 'likeCnt', 'studyCnt', 'isForHomework', 'studies', 'title', 'description', 'difficulty', 'requiredTime', 'user', 'parent', 'created', 'updated']

,_id,goals,visit,visitedUsers,savedUsers,like,comment,likeCnt,studyCnt,isForHomework,studies,title,description,difficulty,requiredTime,user,parent,created,updated
0,{'$oid': '64f128290fb740002c925746'},[이미지 인식을 적용한 사물 인식 모델을 활용해 그림 맞히기 게임을 만들 수 있다.],2,[],[],[],0,0,0,False,[{'$oid': '64f128290fb740002c925759'}],2-1-03. 그림 맞히기 게임 만들기,"<비상교육 인공지능 기초 교과서 46~50쪽>\n이미지 인식을 이해하고, 엔트리 프...",1,5,{'$oid': '60d073cb9d0f630d5ef4a32e'},{'$oid': '61370a9c8cfe850116268bed'},{'$date': '2023-08-31T23:54:17.717Z'},{'$date': '2023-09-01T01:28:42.479Z'}
1,{'$oid': '64f1249bd6c83a002592aa22'},[변수를 활용하여 묻고 대답하기 연습],36,[],"[{'$oid': '6243facb7d826a006ef1006f'}, {'$oid'...",[],0,0,0,True,[{'$oid': '64f1249bd6c83a002592aa35'}],3차시-변수를 활용하여 묻고 대답하기 연습,변수를 활용하여 묻고 대답하기 연습,1,1,{'$oid': '6243facb7d826a006ef1006f'},{'$oid': '64ebf97e93f9ee00255ee6f4'},{'$date': '2023-08-31T23:39:07.887Z'},{'$date': '2023-09-01T01:35:40.363Z'}
2,{'$oid': '64f1232ae833e5001a48fdc2'},[피겨 선수를 만나는 프로그램 만들기],1,[],[],[],0,0,0,False,[{'$oid': '64f1232ae833e5001a48fdc3'}],피겨 선수를 만나는 프로그램 만들기,순차 구조를 이용하여 피겨 선수를 만나는 프로그램을 만들어 봅시다.,1,1,{'$oid': '64b73146de7f3a002cbb8c0a'},NaN,{'$date': '2023-08-31T23:32:59.456Z'},{'$date': '2023-08-31T23:32:59.456Z'}

[JSON] newlectures_5.json
type: <class 'list'>
sample keys: ['_id', 'title', 'description', 'goals', 'requiredTime', 'difficulty', 'user', 'visit', 'visitedUsers', 'savedUsers', 'like', 'comment', 'likeCnt', 'studyCnt', 'isForHomework', 'parent', 'studies', 'created', 'updated']

,_id,title,description,goals,requiredTime,difficulty,user,visit,visitedUsers,savedUsers,like,comment,likeCnt,studyCnt,isForHomework,parent,studies,created,updated,category
0,{'$oid': '66d25bf2e83893ef7b8b8502'},동물 친구 이야기 만들기,▶ 무엇을 만들어 볼까?\n강아지와 고양이가 대화하고 달리는 모습을 만들어봅시다.\...,"[순서대로 블록을 조립하여 오브젝트간 대화를 만들 수 있다., 두 개의 오브젝트를 ...",3,1,{'$oid': '66d25bf2e83893ef7b8b84d1'},0,[],[],[],0,0,0,False,{'$oid': '59018c767baa939aeae08910'},[{'$oid': '59004d7dc5a92b3617557294'}],{'$date': '2024-08-30T23:55:30.902Z'},{'$date': '2024-08-30T23:55:30.902Z'},NaN
1,{'$oid': '66d1e468786d91241ff613af'},두더지 게임 만들기,"장면변화, 신호보내기, 글상자등을 이용한\n두더지 게임을 구현해보자","[장면의 이동을 배워보자, 오브젝트간의 통신을 위한 신호보내기에 대해 알아보자, 글...",5,2,{'$oid': '6265f13cfae91604ca622195'},5,[],[],[],0,0,0,True,{'$oid': '66d1e3d3cb70ee165007a732'},[{'$oid': '66d1e468786d91241ff613c2'}],{'$date': '2024-08-30T15:25:29.137Z'},{'$date': '2024-08-30T15:25:29.137Z'},NaN
2,{'$oid': '66d1c5cefdd085735d76aa88'},01.[순차] 멍멍이와 야옹이가 인사해요,학교에서 친구들과 종이접기를 해본 경험이 있나요? 종이접기 책을 보며 순서에 따라 ...,[멍이와 냥이의 블록이 각각 동시에 실행됨을 알고 ‘기다리기’ 블록을 이용하여 대화...,1,1,{'$oid': '66d1c5cdfdd085735d76a9d3'},0,[],[],[],0,0,2735,True,{'$oid': '56434d26d853c043040ab098'},[{'$oid': '586c6076076231d29300a695'}],{'$date': '2024-08-30T13:14:54.513Z'},{'$date': '2024-08-30T13:14:54.513Z'},category_etc

In [7]:
from pathlib import Path
import re, json
import pandas as pd

BASE = Path(r"C:\Users\PC\Desktop\chatbot\dataset")
OUT  = BASE / "built"
OUT.mkdir(parents=True, exist_ok=True)

def to_bool(x):
    if isinstance(x, bool): return x
    if x is None: return False
    return str(x).strip().lower() in ("true","1","yes","y","t")

def non_empty_text(x):
    if x is None: return False
    if isinstance(x, (list, tuple)):  # 리스트형 goals 지원
        return any(str(t).strip() for t in x)
    return len(str(x).strip()) > 0

def clean_text(s):
    if s is None: return ""
    s = re.sub(r"<[^>]+>", " ", str(s))
    s = re.sub(r"\s+", " ", s).strip()
    return s

def difficulty_to_int(x):
    if x is None: return 1
    s = str(x).strip().lower()
    if s in ("1","beginner","초급"): return 1
    if s in ("2","intermediate","중급"): return 2
    if s in ("3","advanced","고급"): return 3
    try:
        v = int(float(s)); return v if v in (1,2,3) else 1
    except: return 1

def make_discovery_url(any_id):
    if not any_id: return None
    s = str(any_id)
    m = re.search(r'([0-9a-fA-F]{24})', s)
    return f"https://playentry.org/discovery/{m.group(1)}" if m else f"https://playentry.org/discovery/{s}"

def normalize_row(row: dict, kind: str):
    if kind == "discovery":
        # 필터: isopen == true
        if not to_bool(row.get("isopen")):
            return None
        # goal (단수)
        goal = row.get("goal")
        if not non_empty_text(goal):
            return None
        goal_text = clean_text(goal)
        _id = row.get("_id") or row.get("id")
        title = clean_text(row.get("title"))
        # summary 우선, 없으면 description
        summary = clean_text(row.get("summary") or row.get("description"))
        category = str(row.get("categoryCode") or "general").strip()
        diff = difficulty_to_int(row.get("difficulty"))
        url = make_discovery_url(_id)
        search_text = " ".join([title, summary, goal_text]).strip()
        return {
            "id": str(_id) if _id else "",
            "title": title,
            "category": category,
            "difficulty": diff,
            "url": url,
            "search_text": search_text
        }

    elif kind == "newlectures":
        # 필터: goals 필드가 비어있지 않음 (리스트/문자열 모두 허용)
        goals = row.get("goals")
        if not non_empty_text(goals):
            return None
        # 리스트면 문장으로 합치기
        if isinstance(goals, (list, tuple)):
            goals_text = " ".join(clean_text(g) for g in goals if str(g).strip())
        else:
            goals_text = clean_text(goals)

        _id = row.get("_id") or row.get("id")
        title = clean_text(row.get("title"))
        desc  = clean_text(row.get("description"))
        category = str(row.get("category") or "general").strip()
        diff = difficulty_to_int(row.get("difficulty"))
        url = None  # newlectures는 별도 링크 규칙 없음
        search_text = " ".join([title, desc, goals_text]).strip()
        return {
            "id": str(_id) if _id else "",
            "title": title,
            "category": category,
            "difficulty": diff,
            "url": url,
            "search_text": search_text
        }

    else:
        return None

In [8]:
def load_json(path: Path):
    """
    지원:
      1) 배열형 JSON: [ {...}, {...} ]
      2) JSON Lines: 한 줄에 한 객체
      3) }{ 로 붙은 비표준: {"a":1}{"b":2}  → 중간에 , 넣어 []로 감싸 파싱
      4) { data: [...]} / { items: [...] } 래퍼
    """
    txt = path.read_text(encoding="utf-8", errors="ignore").strip()

    # 1) 배열형
    if txt.startswith("[") and txt.endswith("]"):
        return json.loads(txt)

    # 2) JSONL 시도
    lines = [ln.strip() for ln in txt.splitlines() if ln.strip()]
    if len(lines) > 1:
        rows = []
        ok = True
        for ln in lines:
            try:
                rows.append(json.loads(ln))
            except Exception:
                ok = False
                break
        if ok:
            return rows

    # 3) }{ 비표준 → },{ 로 패치 후 []로 감싸기
    patched = "[" + re.sub(r"}\s*{", "},{", txt) + "]"
    try:
        return json.loads(patched)
    except Exception:
        pass

    # 4) 래퍼 객체
    try:
        obj = json.loads(txt)
        return obj.get("data") or obj.get("items") or []
    except Exception as e:
        print(f"[load_json] {path.name} 파싱 실패: {e}")
        return []


def load_csv(path: Path):
    # 인코딩 이슈 대비
    for enc in ("utf-8-sig", "utf-8", "cp949"):
        try:
            df = pd.read_csv(path, dtype="object", encoding=enc).fillna("")
            return [dict(r) for _, r in df.iterrows()]
        except Exception:
            continue
    raise RuntimeError(f"[load_csv] {path} CSV를 읽을 수 없습니다. (인코딩 확인)")


def save_json(path: Path, rows):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(rows, ensure_ascii=False, indent=2), encoding="utf-8")

In [9]:
discovery_inputs = [
    ("discovery_3.csv",  "discovery"),
    ("discovery_4.json", "discovery"),
    ("discovery_5.json", "discovery"),
]

all_disc = []

for fname, kind in discovery_inputs:
    p = BASE / fname
    rows = load_csv(p) if p.suffix == ".csv" else load_json(p)
    normed = [r for r in (normalize_row(r, kind) for r in rows) if r]
    save_json(OUT / f"{p.stem}_filtered.json", normed)
    print(f"{fname:16s} → kept {len(normed)} / {len(rows)}")
    all_disc.extend(normed)

# id 기준 중복 제거(마지막 레코드 우선)
merged_disc = list({r["id"]: r for r in all_disc}.values())
save_json(OUT / "discovery_merged.json", merged_disc)
print("discovery_merged.json:", len(merged_disc), "rows")

discovery_3.csv  → kept 31 / 38
discovery_4.json → kept 1 / 3
discovery_5.json → kept 3 / 5
discovery_merged.json: 35 rows

In [11]:
import pandas as pd

print("== Discovery sample ==")
display(pd.DataFrame((BASE/"built"/"discovery_merged.json").read_text(encoding="utf-8") and
                     json.loads((BASE/"built"/"discovery_merged.json").read_text(encoding="utf-8"))[:3]))

print("== Newlectures sample ==")
display(pd.DataFrame((BASE/"built"/"newlectures_merged.json").read_text(encoding="utf-8") and
                     json.loads((BASE/"built"/"newlectures_merged.json").read_text(encoding="utf-8"))[:3]))

== Discovery sample ==

,id,title,category,difficulty,url,search_text
0,ObjectId(61d2a6ea94a125003f94e23c),클릭! 나무 키우기,game,1,https://playentry.org/discovery/61d2a6ea94a125...,클릭! 나무 키우기 클릭하다 보니 어느새 나무가 다 자랐다 클릭으로 즐기는 무한의 ...
1,ObjectId(61d68107ec9979003fb71fb8),"와썹, 콧수염 셀카!",living,1,https://playentry.org/discovery/61d68107ec9979...,"와썹, 콧수염 셀카! 인공지능이 만들어 주는 멋진 콧수염 얼굴 인식을 이용해 AR ..."
2,ObjectId(61d68ad5ec9979003fb71fb9),종이접기의 세계,knowledge,2,https://playentry.org/discovery/61d68ad5ec9979...,종이접기의 세계 이런 것도 접을 수 있다고? 나만의 종이접기 방법을 공유하는 작품을...

== Newlectures sample ==

,id,title,category,difficulty,url,search_text
0,ObjectId(63b0b90504f9b1002ce5764b),벽 부수기,general,3,None,"벽 부수기 벽을 많이 부숴 이기세요 [""인작이 목표""]"
1,ObjectId(63b0659ede65ed001a3127c5),동물 친구 이야기 만들기,general,1,None,동물 친구 이야기 만들기 ▶ 무엇을 만들어 볼까? 강아지와 고양이가 대화하고 달리는...
2,ObjectId(63b03eb3c69327004916022b),Q&A,general,1,None,"Q&A 저의 여러가지 궁금하던 점을 풀어보는 볼수있도록 준비하는 기간 [""엔둥이들이..."

In [14]:
from pathlib import Path
import pandas as pd, json, re

BASE = Path(r"C:\Users\PC\Desktop\chatbot\dataset")
OUT  = BASE / "built"
OUT.mkdir(parents=True, exist_ok=True)

lec_csv = BASE / "entry_lectures_title_utf8.csv"  # 새로 저장한 파일명
df_lec = pd.read_csv(lec_csv, dtype="object", encoding="utf-8").fillna("")
print(len(df_lec), "rows")
print(list(df_lec.columns)[:10])
df_lec.head(3)

392 rows
['id', 'url', 'title', 'difficulty', 'category', 'description', 'goal']

,id,url,title,difficulty,category,description,goal
0,57170ad9b412d36633cf2d5d,https://playentry.org/study/lecture/57170ad9b4...,[Vol.3] 대한민국 지도 퍼즐,쉬움,기타,엔트리로 대한민국 지도 퍼즐을 만들어보면서 우리 국토에 대해 공부해봅시다. 마우스로...,오브젝트를 여러 개 가진 퍼즐 작품을 만들 수 있다. | 마우스로 드래그하여 퍼즐조...
1,57170d5b7e8cc2e971057723,https://playentry.org/study/lecture/57170d5b7e...,[Vol.3] 퍼즐을 맞추면 지역 이름이 뜨도록 하기,중간,기타,이번엔 퍼즐을 알맞은 위치에 맞추었을 때 변수 값을 지역이름으로 바꿀 수 있도록 블...,변수를 사용할 수 있다. | 퍼즐을 알맞은 위치에 맞추었을 때 변수 값을 지역 이름...
2,57170fd6bba8e81d72043698,https://playentry.org/study/lecture/57170fd6bb...,[Vol.3] 벚꽃 애니메이션,중간,1시간 이상기타,벚꽃이 만개하는 4월입니다. \n그동안 예쁜 벚꽃들이 흩날리는 모습을 눈으로만 느꼈...,신호를 활용하여 벚꽃이 만개하면 꽃잎이 떨어지기 시작하도록 만들 수 있다. | 복제...

In [15]:
def clean_text(s):
    if s is None: return ""
    s = re.sub(r"<[^>]+>", " ", str(s))
    s = re.sub(r"\s+", " ", s).strip()
    return s

def difficulty_to_int(x):
    if x is None: return 1
    s = str(x).strip().lower()
    if s in ("1","beginner","초급"): return 1
    if s in ("2","intermediate","중급"): return 2
    if s in ("3","advanced","고급"): return 3
    try:
        v = int(float(s)); return v if v in (1,2,3) else 1
    except: return 1

In [16]:
def normalize_lecture_row(row: dict):
    any_id = row.get("_id") or row.get("id") or row.get("lectureId") or row.get("uuid")
    title  = row.get("title") or row.get("name") or row.get("lecture_title") or ""
    title  = clean_text(title)
    if not title:
        return None

    desc   = clean_text(row.get("description") or row.get("summary") or row.get("content") or "")
    goals  = row.get("goals") or row.get("goal") or row.get("objectives") or ""
    if isinstance(goals, (list, tuple)):
        goals_text = " ".join(clean_text(g) for g in goals if str(g).strip())
    else:
        goals_text = clean_text(goals)

    category = str(row.get("category") or row.get("categoryCode") or "general").strip()
    diff     = difficulty_to_int(row.get("difficulty"))
    url      = row.get("url")
    url      = url if url and str(url).strip() else None

    search_text = " ".join([title, desc, goals_text]).strip()

    return {
        "id": str(any_id) if any_id else title,   # id 없으면 title 사용
        "title": title,
        "category": category,
        "difficulty": diff,
        "url": url,
        "search_text": search_text
    }

In [17]:
def normalize_lecture_row(row: dict):
    any_id = row.get("_id") or row.get("id") or row.get("lectureId") or row.get("uuid")
    title  = row.get("title") or row.get("name") or row.get("lecture_title") or ""
    title  = clean_text(title)
    if not title:
        return None

    desc   = clean_text(row.get("description") or row.get("summary") or row.get("content") or "")
    goals  = row.get("goals") or row.get("goal") or row.get("objectives") or ""
    if isinstance(goals, (list, tuple)):
        goals_text = " ".join(clean_text(g) for g in goals if str(g).strip())
    else:
        goals_text = clean_text(goals)

    category = str(row.get("category") or row.get("categoryCode") or "general").strip()
    diff     = difficulty_to_int(row.get("difficulty"))
    url      = row.get("url")
    url      = url if url and str(url).strip() else None

    search_text = " ".join([title, desc, goals_text]).strip()

    return {
        "id": str(any_id) if any_id else title,   # id 없으면 title 사용
        "title": title,
        "category": category,
        "difficulty": diff,
        "url": url,
        "search_text": search_text
    }

In [18]:
rows = [normalize_lecture_row(r) for _, r in df_lec.iterrows()]
rows = [r for r in rows if r]
rows = list({r["id"]: r for r in rows}.values())   # id 기준 dedup(마지막 우선)

(OUT / "lectures_filtered.json").write_text(
    json.dumps(rows, ensure_ascii=False, indent=2), encoding="utf-8"
)
print("lectures_filtered.json:", len(rows), "rows")

lectures_filtered.json: 392 rows

In [19]:
disc_path = OUT / "discovery_merged.json"  # 앞에서 만든 파일
discovery = json.loads(disc_path.read_text(encoding="utf-8")) if disc_path.exists() else []
lectures  = json.loads((OUT / "lectures_filtered.json").read_text(encoding="utf-8"))

combined = {}
for r in discovery + lectures:
    combined[r["id"]] = r
combined_list = list(combined.values())

(OUT / "contents_merged.json").write_text(
    json.dumps(combined_list, ensure_ascii=False, indent=2), encoding="utf-8"
)
print("contents_merged.json:", len(combined_list), "rows")

contents_merged.json: 427 rows

In [22]:
# pip install sentence-transformers
from sentence_transformers import SentenceTransformer
import numpy as np, pickle, json

model = SentenceTransformer("snunlp/KR-SBERT-V40K-klueNLI-augSTS")

items = json.loads((OUT / "contents_merged.json").read_text(encoding="utf-8"))
texts = [it["search_text"] for it in items]
embs  = model.encode(texts, convert_to_numpy=True, show_progress_bar=True)

obj = {
    "embeddings": embs,
    "metadata": [
        {"id": it["id"], "title": it["title"], "category": it["category"],
         "difficulty": it["difficulty"], "url": it["url"]}
        for it in items
    ]
}

out_pkl = OUT / "contents_embeddings.pkl"
with open(out_pkl, "wb") as f:
    pickle.dump(obj, f)

print("✅ 저장:", out_pkl, "| shape:", embs.shape)

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

C:\Users\PC\anaconda3\Lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\PC\.cache\huggingface\hub\models--snunlp--KR-SBERT-V40K-klueNLI-augSTS. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

config_sentence_transformers.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/707 [00:00<?, ?B/s]

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`

pytorch_model.bin:   0%|          | 0.00/467M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/394 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/467M [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Batches:   0%|          | 0/14 [00:00<?, ?it/s]

✅ 저장: C:\Users\PC\Desktop\chatbot\dataset\built\contents_embeddings.pkl | shape: (427, 768)

In [23]:
import pandas as pd, json, re, pickle
from pathlib import Path
from sentence_transformers import SentenceTransformer
import numpy as np

BASE = Path(r"C:\Users\PC\Desktop\chatbot\dataset")
OUT  = BASE / "built"
OUT.mkdir(parents=True, exist_ok=True)

def clean(s):
    if s is None: return ""
    s = re.sub(r"<[^>]+>", " ", str(s))
    s = re.sub(r"\s+", " ", s).strip()
    return s

def diff_to_int(x):
    if x is None: return 1
    s = str(x).strip().lower()
    if s in ("1","beginner","초급"): return 1
    if s in ("2","intermediate","중급"): return 2
    if s in ("3","advanced","고급"): return 3
    try:
        v = int(float(s)); return v if v in (1,2,3) else 1
    except: return 1

# --- 1. textbook CSV 읽기 ---
textbook_csv = BASE / "entry_textbook.csv"
df_text = pd.read_csv(textbook_csv, dtype="object", encoding="utf-8").fillna("")

def normalize_textbook_row(r):
    _id   = (r.get("id") or "").strip()
    title = clean(r.get("title"))
    goal  = clean(r.get("goal"))
    if not title or not goal:
        return None

    desc  = clean(r.get("description"))
    cat   = (r.get("category") or "general").strip()
    diff  = diff_to_int(r.get("difficulty"))
    url   = (r.get("url") or "").strip() or None

    return {
        "id": _id if _id else title,
        "title": title,
        "category": cat,
        "difficulty": diff,
        "url": url,
        "search_text": " ".join([title, desc, goal]).strip()
    }

textbook = [normalize_textbook_row(r) for _, r in df_text.iterrows()]
textbook = [r for r in textbook if r]
print("✅ textbook rows:", len(textbook))

# --- 2. discovery + lectures 불러오기 ---
discovery = json.loads((OUT/"discovery_merged.json").read_text(encoding="utf-8"))
lectures  = json.loads((OUT/"lectures_filtered.json").read_text(encoding="utf-8"))

# --- 3. 합치기 + id dedup ---
combined = {}
for r in discovery + lectures + textbook:
    combined[r["id"]] = r
all_items = list(combined.values())
print("전체 콘텐츠:", len(all_items))

# --- 4. 임베딩 ---
model = SentenceTransformer("snunlp/KR-SBERT-V40K-klueNLI-augSTS")
texts = [it["search_text"] for it in all_items]
embs  = model.encode(texts, convert_to_numpy=True, show_progress_bar=True)

store = {
    "embeddings": embs,
    "metadata": [
        {"id": it["id"], "title": it["title"], "category": it["category"],
         "difficulty": it["difficulty"], "url": it["url"]}
        for it in all_items
    ]
}

out_pkl = OUT / "contents_embeddings.pkl"
with open(out_pkl, "wb") as f:
    pickle.dump(store, f)

print("✅ 저장 완료:", out_pkl, "| shape:", embs.shape)

✅ textbook rows: 31
전체 콘텐츠: 458

Batches:   0%|          | 0/15 [00:00<?, ?it/s]

✅ 저장 완료: C:\Users\PC\Desktop\chatbot\dataset\built\contents_embeddings.pkl | shape: (458, 768)